import requests


def get_weather(zipcode, countrycode):
    # Weather API endpoint (https://openweathermap.org)
    weather_endpoint = 'api.openweathermap.org/data/2.5/weather'

    # Parameter(s) needed to make the API call
    payload = {
        'zip' = zipcode
    }

    response = requests.get(url)

def read_config():


def main():
    country_code_map = {
        'Afghanistan': 'AF',
        'Algeria': 'DZ',
        'Argentina': 'AR',
        'Armenia': 'AM',
        'Australia': 'AU',
        'Austria': 'AT',
        'Bahamas': 'BS',
        'Bangladesh': 'BD',
        'Barbados': 'BB',
        'Belgium': 'BE',
        'Belize': 'BZ',
        'Bhutan': 'BT',
        'Bolivia': 'BO',
        'Bosnia and Herzegovina': 'BA',
        'Botswana': 'BW',
        'Brazil': 'BR',
        'Bulgaria': 'BG',
        'Cambodia': 'KH',
        'Cameroon': 'CM',
        'Canada': 'CA',
        'Chad': 'TD',
        'Chile': 'CL',
        'China': 'CN',
        'Colombia': 'CO',
        'Congo': 'CG',
        'Costa Rica': 'CR',
        'Croatia': 'HR',
        'Cuba': 'CU',
        'Czech Republic': 'CZ',
        'Denmark': 'DK',
        'Dominican Republic': 'DO',
        'Ecuador': 'EC',
        'Egypt': 'EG',
        'El Salvador': 'SV',
        'Estonia': 'EE',
        'Ethiopia': 'ET',
        'Finland': 'FI',
        'France': 'FR',
        'Germany': 'DE',
        'Ghana': 'GH',
        'Greece': 'GR',
        'Greenland': 'GL',
        'Guadeloupe': 'GP',
        'Guatemala': 'GT',
        'Guinea': 'GN',
        'Haiti': 'HT',
        'Honduras': 'HN',
        'Hong Kong': 'HK',
        'Hungary': 'HU',
        'Iceland': 'IS',
        'India': 'IN',
        'Indonesia': 'ID',
        'Iraq': 'IQ',
        'Ireland': 'IE',
        'Israel': 'IL',
        'Italy': 'IT',
        'Jamaica': 'JM',
        'Japan': 'JP',
        'Jordan': 'JO',
        'Kenya': 'KE',
        'Kuwait': 'KW',
        'Latvia': 'LV',
        'Lebanon': 'LB',
        'Liberia': 'LR',
        'Libya': 'LY',
        'Lithuania': 'LT',
        'Luxembourg': 'LU',
        'Macao': 'MO',
        'Madagascar': 'MG',
        'Malaysia': 'MY',
        'Mexico': 'MX',
        'Mongolia': 'MN',
        'Morocco': 'MA',
        'Myanmar': 'MM',
        'Nepal': 'NP',
        'Netherlands': 'NL',
        'New Zealand': 'NZ',
        'Nicaragua': 'NI',
        'Niger': 'NE',
        'Nigeria': 'NG',
        'Norway': 'NO',
        'Pakistan': 'PK',
        'Panama': 'PA',
        'Papua New Guinea': 'PG',
        'Paraguay': 'PY',
        'Peru': 'PE',
        'Philippines': 'PH',
        'Poland': 'PL',
        'Portugal': 'PT',
        'Puerto Rico': 'PR',
        'Romania': 'RO',
        'Russian Federation': 'RU',
        'Saudi Arabia': 'SA',
        'Serbia': 'RS',
        'Sierra Leone': 'SL',
        'Singapore': 'SG',
        'Slovakia': 'SK',
        'Slovenia': 'SI',
        'Somalia': 'SO',
        'South Africa': 'ZA',
        'South Korea': 'KR',
        'South Sudan': 'SS',
        'Spain': 'ES',
        'Sri Lanka': 'LK',
        'Sudan': 'SD',
        'Sweden': 'SE',
        'Switzerland': 'CH',
        'Taiwan': 'TW',
        'Thailand': 'TH',
        'Turkey': 'TR',
        'Uganda': 'UG',
        'Ukraine': 'UA',
        'United Kingdom': 'GB',
        'United Republic of Tanzania': 'TZ',
        'United States': 'US',
        'Uruguay': 'UY',
        'Uzbekistan': 'UZ',
        'Venezuela': 'VE',
        'Vietnam': 'VN',
        'Western Sahara': 'EH',
        'Yemen': 'YE',
        'Zambia': 'ZM',
        'Zimbabwe': 'ZW'
    }

    
    weather_apikey =

main()

